INTENTS = {
    "status": ["durum", "durum lumos", "proje durum", "aktif mi", "proje"],
    "greeting": ["naber", "napıyorsun", "ne yapıyorsun", "napion", "napiyon", "napan"],
    "reason": ["neden", "niye"],
    "help": ["yardım", "yardim", "help", "komut"],
    "recent": ["son eklenen", "son eklenenler"],
    "changes": [
        "değişiklik",
        "degisiklik",
        "yapılan değişiklikler",
        "neler değişti",
        "ne değişti",
    ],
    "last_output": ["ne diyor", "ne çıktı", "özetle", "acikla", "açıkla"],
    "suggest": [
        "öner",
        "oner",
        "sıradaki",
        "siradaki",
        "ne yapayım",
        "öneri",
        "öneriler",
        "önerilere",
    ],
    "stable": ["stabil"],
    "continue": ["devam"],
    "version": ["version", "sürüm", "surum"],
    "health": ["health", "sağlık", "saglik"],
}
